In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

In [2]:
digits=load_digits()

In [3]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [4]:
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [5]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)



C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9462962962962963

In [6]:
rf=RandomForestClassifier(n_estimators=50)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9648148148148148

In [7]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9814814814814815

In [8]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
kf.split([1,2,3,4,5,6,7,8,9])

<generator object _BaseKFold.split at 0x000002A223EC9190>

In [10]:
for train_index ,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
def getScore (model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [12]:
getScore(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9462962962962963

In [13]:
getScore(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9629629629629629

In [14]:
getScore(SVC(),X_train,X_test,y_train,y_test)

0.9814814814814815

In [15]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=3)
score_logistic=[]
score_svm=[]
score_random_f=[]
for train_index,test_index in skf.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index], digits.target[train_index],digits.target[test_index]
    score_logistic.append(getScore(LogisticRegression(),X_train,X_test,y_train,y_test))
    score_svm.append(getScore(SVC(),X_train,X_test,y_train,y_test))    
    score_random_f.append(getScore(RandomForestClassifier(),X_train,X_test,y_train,y_test))    

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

In [16]:
score_random_f

[0.9298831385642737, 0.9649415692821369, 0.9232053422370617]

In [17]:
score_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [18]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [24]:
cross_val_score(SVC(),digits.data,digits.target,cv=8)


array([0.95555556, 0.97777778, 0.95555556, 0.98666667, 0.98666667,
       0.98660714, 0.98214286, 0.91517857])

In [22]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)


array([0.93055556, 0.89722222, 0.96100279, 0.96100279, 0.92479109])

In [25]:
scoree1=cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target,cv=10)

In [26]:
np.average(

0.9176350093109871

In [27]:
scoree1.mean()

0.9176350093109871