In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np

In [2]:
df=pd.read_csv('E:\csv files\canadaincome.csv')

In [3]:
df

year  per capita income (US$)    Unnamed: 2  Unnamed: 3  Unnamed: 4
0    NaN                     1970   3399.299037         NaN         NaN
1    NaN                     1971   3768.297935         NaN         NaN
2    NaN                     1972   4251.175484         NaN         NaN
3    NaN                     1973   4804.463248         NaN         NaN
4    NaN                     1974   5576.514583         NaN         NaN
5    NaN                     1975   5998.144346         NaN         NaN
6    NaN                     1976   7062.131392         NaN         NaN
7    NaN                     1977   7100.126170         NaN         NaN
8    NaN                     1978   7247.967035         NaN         NaN
9    NaN                     1979   7602.912681         NaN         NaN
10   NaN                     1980   8355.968120         NaN         NaN
11   NaN                     1981   9434.390652         NaN         NaN
12   NaN                     1982   9619.438377         NaN         NaN
13   NaN                     1983  10416.536590         NaN         NaN
14   NaN                     1984  10790.328720         NaN         NaN
15   NaN                     1985  11018.955850         NaN         NaN
16   NaN                     1986  11482.891530         NaN         NaN
17   NaN                     1987  12974.806620         NaN         NaN
18   NaN                     1988  15080.283450         NaN         NaN
19   NaN                     1989  16426.725480         NaN         NaN
20   NaN                     1990  16838.673200         NaN         NaN
21   NaN                     1991  17266.097690         NaN         NaN
22   NaN                     1992  16412.083090         NaN         NaN
23   NaN                     1993  15875.586730         NaN         NaN
24   NaN                     1994  15755.820270         NaN         NaN
25   NaN                     1995  16369.317250         NaN         NaN
26   NaN                     1996  16699.826680         NaN         NaN
27   NaN                     1997  17310.757750         NaN         NaN
28   NaN                     1998  16622.671870         NaN         NaN
29   NaN                     1999  17581.024140         NaN         NaN
30   NaN                     2000  18987.382410         NaN         NaN
31   NaN                     2001  18601.397240         NaN         NaN
32   NaN                     2002  19232.175560         NaN         NaN
33   NaN                     2003  22739.426280         NaN         NaN
34   NaN                     2004  25719.147150         NaN         NaN
35   NaN                     2005  29198.055690         NaN         NaN
36   NaN                     2006  32738.262900         NaN         NaN
37   NaN                     2007  36144.481220         NaN         NaN
38   NaN                     2008  37446.486090         NaN         NaN
39   NaN                     2009  32755.176820         NaN         NaN
40   NaN                     2010  38420.522890         NaN         NaN
41   NaN                     2011  42334.711210         NaN         NaN
42   NaN                     2012  42665.255970         NaN         NaN
43   NaN                     2013  42676.468370         NaN         NaN
44   NaN                     2014  41039.893600         NaN         NaN
45   NaN                     2015  35175.188980         NaN         NaN
46   NaN                     2016           NaN         NaN         NaN

In [19]:
df1=df.drop(columns=['year','Unnamed: 3','Unnamed: 4'])
df1

per capita income (US$)    Unnamed: 2
0                      1970   3399.299037
1                      1971   3768.297935
2                      1972   4251.175484
3                      1973   4804.463248
4                      1974   5576.514583
5                      1975   5998.144346
6                      1976   7062.131392
7                      1977   7100.126170
8                      1978   7247.967035
9                      1979   7602.912681
10                     1980   8355.968120
11                     1981   9434.390652
12                     1982   9619.438377
13                     1983  10416.536590
14                     1984  10790.328720
15                     1985  11018.955850
16                     1986  11482.891530
17                     1987  12974.806620
18                     1988  15080.283450
19                     1989  16426.725480
20                     1990  16838.673200
21                     1991  17266.097690
22                     1992  16412.083090
23                     1993  15875.586730
24                     1994  15755.820270
25                     1995  16369.317250
26                     1996  16699.826680
27                     1997  17310.757750
28                     1998  16622.671870
29                     1999  17581.024140
30                     2000  18987.382410
31                     2001  18601.397240
32                     2002  19232.175560
33                     2003  22739.426280
34                     2004  25719.147150
35                     2005  29198.055690
36                     2006  32738.262900
37                     2007  36144.481220
38                     2008  37446.486090
39                     2009  32755.176820
40                     2010  38420.522890
41                     2011  42334.711210
42                     2012  42665.255970
43                     2013  42676.468370
44                     2014  41039.893600
45                     2015  35175.188980
46                     2016           NaN

In [25]:
df2=df1.rename({'per capita income (US$)':'year','Unnamed: 2':'per_capita_income'},axis=1)

In [26]:
df2

year  per_capita_income
0   1970        3399.299037
1   1971        3768.297935
2   1972        4251.175484
3   1973        4804.463248
4   1974        5576.514583
5   1975        5998.144346
6   1976        7062.131392
7   1977        7100.126170
8   1978        7247.967035
9   1979        7602.912681
10  1980        8355.968120
11  1981        9434.390652
12  1982        9619.438377
13  1983       10416.536590
14  1984       10790.328720
15  1985       11018.955850
16  1986       11482.891530
17  1987       12974.806620
18  1988       15080.283450
19  1989       16426.725480
20  1990       16838.673200
21  1991       17266.097690
22  1992       16412.083090
23  1993       15875.586730
24  1994       15755.820270
25  1995       16369.317250
26  1996       16699.826680
27  1997       17310.757750
28  1998       16622.671870
29  1999       17581.024140
30  2000       18987.382410
31  2001       18601.397240
32  2002       19232.175560
33  2003       22739.426280
34  2004       25719.147150
35  2005       29198.055690
36  2006       32738.262900
37  2007       36144.481220
38  2008       37446.486090
39  2009       32755.176820
40  2010       38420.522890
41  2011       42334.711210
42  2012       42665.255970
43  2013       42676.468370
44  2014       41039.893600
45  2015       35175.188980
46  2016                NaN

In [27]:
df2

year  per_capita_income
0   1970        3399.299037
1   1971        3768.297935
2   1972        4251.175484
3   1973        4804.463248
4   1974        5576.514583
5   1975        5998.144346
6   1976        7062.131392
7   1977        7100.126170
8   1978        7247.967035
9   1979        7602.912681
10  1980        8355.968120
11  1981        9434.390652
12  1982        9619.438377
13  1983       10416.536590
14  1984       10790.328720
15  1985       11018.955850
16  1986       11482.891530
17  1987       12974.806620
18  1988       15080.283450
19  1989       16426.725480
20  1990       16838.673200
21  1991       17266.097690
22  1992       16412.083090
23  1993       15875.586730
24  1994       15755.820270
25  1995       16369.317250
26  1996       16699.826680
27  1997       17310.757750
28  1998       16622.671870
29  1999       17581.024140
30  2000       18987.382410
31  2001       18601.397240
32  2002       19232.175560
33  2003       22739.426280
34  2004       25719.147150
35  2005       29198.055690
36  2006       32738.262900
37  2007       36144.481220
38  2008       37446.486090
39  2009       32755.176820
40  2010       38420.522890
41  2011       42334.711210
42  2012       42665.255970
43  2013       42676.468370
44  2014       41039.893600
45  2015       35175.188980
46  2016                NaN

In [31]:
df3=df2.dropna()
df3

year  per_capita_income
0   1970        3399.299037
1   1971        3768.297935
2   1972        4251.175484
3   1973        4804.463248
4   1974        5576.514583
5   1975        5998.144346
6   1976        7062.131392
7   1977        7100.126170
8   1978        7247.967035
9   1979        7602.912681
10  1980        8355.968120
11  1981        9434.390652
12  1982        9619.438377
13  1983       10416.536590
14  1984       10790.328720
15  1985       11018.955850
16  1986       11482.891530
17  1987       12974.806620
18  1988       15080.283450
19  1989       16426.725480
20  1990       16838.673200
21  1991       17266.097690
22  1992       16412.083090
23  1993       15875.586730
24  1994       15755.820270
25  1995       16369.317250
26  1996       16699.826680
27  1997       17310.757750
28  1998       16622.671870
29  1999       17581.024140
30  2000       18987.382410
31  2001       18601.397240
32  2002       19232.175560
33  2003       22739.426280
34  2004       25719.147150
35  2005       29198.055690
36  2006       32738.262900
37  2007       36144.481220
38  2008       37446.486090
39  2009       32755.176820
40  2010       38420.522890
41  2011       42334.711210
42  2012       42665.255970
43  2013       42676.468370
44  2014       41039.893600
45  2015       35175.188980

In [36]:
plt.figure(figsize=(12,7))
plt.scatter(df3['year'],df3['per_capita_income'],color='r',marker='*')

In [45]:
plt.figure(figsize=(12,7))

plt.plot(df3.year,df3.per_capita_income,marker='*',color='r')

In [52]:
x_train=df3.drop('per_capita_income',axis=1)
x_test=df3['per_capita_income']

In [63]:
model=linear_model.LinearRegression()
model.fit(x_train,x_test)

LinearRegression()

In [56]:
model.fit(x_train,x_test)

LinearRegression()

In [64]:
model.predict([[2020]])

array([41668.68657478])

In [66]:
model.predict([[2015]])

array([37472.07655861])

In [65]:
df3

year  per_capita_income
0   1970        3399.299037
1   1971        3768.297935
2   1972        4251.175484
3   1973        4804.463248
4   1974        5576.514583
5   1975        5998.144346
6   1976        7062.131392
7   1977        7100.126170
8   1978        7247.967035
9   1979        7602.912681
10  1980        8355.968120
11  1981        9434.390652
12  1982        9619.438377
13  1983       10416.536590
14  1984       10790.328720
15  1985       11018.955850
16  1986       11482.891530
17  1987       12974.806620
18  1988       15080.283450
19  1989       16426.725480
20  1990       16838.673200
21  1991       17266.097690
22  1992       16412.083090
23  1993       15875.586730
24  1994       15755.820270
25  1995       16369.317250
26  1996       16699.826680
27  1997       17310.757750
28  1998       16622.671870
29  1999       17581.024140
30  2000       18987.382410
31  2001       18601.397240
32  2002       19232.175560
33  2003       22739.426280
34  2004       25719.147150
35  2005       29198.055690
36  2006       32738.262900
37  2007       36144.481220
38  2008       37446.486090
39  2009       32755.176820
40  2010       38420.522890
41  2011       42334.711210
42  2012       42665.255970
43  2013       42676.468370
44  2014       41039.893600
45  2015       35175.188980

In [67]:
model.coef_

array([839.32200323])

In [68]:
model.intercept_

-1653761.759955748

In [69]:
#y=m*x+b

In [70]:
839.32200323*2018+(-1653761.759955748)

39990.04256239184

In [71]:
model.predict([[2018]])

array([39990.04256831])

In [72]:
model.predict([[2018]])

array([38311.39856184])

In [73]:
model.predict([[2020]])

array([41668.68657478])