In [1]:
import pandas as pd
import numpy as np

In [18]:
df=pd.read_csv('E:\csv files\cardata.csv')

In [17]:
df

car_models  totl_km  sell_price($)  car_age
0                  bmw x5    69000          18000        3
1                  bmw x5    35000          34000        3
2                  bmw x5    57000          26100        5
3                  bmw x5    22500          40000        2
4                  bmw x5    46000          31500        4
5                 Audi A5    59000          29400        4
6                 Audi A6    25000          32000        5
7                 Audi A5    72000          19300        5
8                 Audi A8    20000          62000        3
9   Mercedez Benz C class    67000          22000        6
10  Mercedez Benz C class    83000          20000        7
11  Mercedez Benz C class    79000          21000        7
12  Mercedez Benz C class    59000          33000        5

In [19]:
df_dummys=pd.get_dummies(df.car_models,drop_first=True)
df_dummys

Audi A6  Audi A8  Mercedez Benz C class  bmw x5
0         0        0                      0       1
1         0        0                      0       1
2         0        0                      0       1
3         0        0                      0       1
4         0        0                      0       1
5         0        0                      0       0
6         1        0                      0       0
7         0        0                      0       0
8         0        1                      0       0
9         0        0                      1       0
10        0        0                      1       0
11        0        0                      1       0
12        0        0                      1       0

In [23]:
df1=pd.concat([df,df_dummys],axis=1)
df1

car_models  totl_km  sell_price($)  car_age  Audi A6  Audi A8  \
0                  bmw x5    69000          18000        3        0        0   
1                  bmw x5    35000          34000        3        0        0   
2                  bmw x5    57000          26100        5        0        0   
3                  bmw x5    22500          40000        2        0        0   
4                  bmw x5    46000          31500        4        0        0   
5                 Audi A5    59000          29400        4        0        0   
6                 Audi A6    25000          32000        5        1        0   
7                 Audi A5    72000          19300        5        0        0   
8                 Audi A8    20000          62000        3        0        1   
9   Mercedez Benz C class    67000          22000        6        0        0   
10  Mercedez Benz C class    83000          20000        7        0        0   
11  Mercedez Benz C class    79000          21000        7        0        0   
12  Mercedez Benz C class    59000          33000        5        0        0   

    Mercedez Benz C class  bmw x5  
0                       0       1  
1                       0       1  
2                       0       1  
3                       0       1  
4                       0       1  
5                       0       0  
6                       0       0  
7                       0       0  
8                       0       0  
9                       1       0  
10                      1       0  
11                      1       0  
12                      1       0

In [25]:
x_train=df1.drop(['car_models','sell_price($)'],axis=1)
x_test=df1['sell_price($)']

In [26]:
x_train

totl_km  car_age  Audi A6  Audi A8  Mercedez Benz C class  bmw x5
0     69000        3        0        0                      0       1
1     35000        3        0        0                      0       1
2     57000        5        0        0                      0       1
3     22500        2        0        0                      0       1
4     46000        4        0        0                      0       1
5     59000        4        0        0                      0       0
6     25000        5        1        0                      0       0
7     72000        5        0        0                      0       0
8     20000        3        0        1                      0       0
9     67000        6        0        0                      1       0
10    83000        7        0        0                      1       0
11    79000        7        0        0                      1       0
12    59000        5        0        0                      1       0

In [28]:
#(#1)audi6,(2)audi8,(3)audi5,(4)mercedez,(5)bmw

In [29]:
from sklearn import linear_model

In [30]:
model=linear_model.LinearRegression()

In [31]:
model.fit(x_train,x_test)

LinearRegression()

In [32]:
model.predict([[40000,0,1,0,0,0]])

array([22351.6765286])

In [33]:
model.predict([[40000,0,0,1,0,0]])

array([50789.98027613])

In [42]:
model.predict([[45000,0,0,1,0,5]])

array([30361.08481262])

In [36]:
df

car_models  totl_km  sell_price($)  car_age
0                  bmw x5    69000          18000        3
1                  bmw x5    35000          34000        3
2                  bmw x5    57000          26100        5
3                  bmw x5    22500          40000        2
4                  bmw x5    46000          31500        4
5                 Audi A5    59000          29400        4
6                 Audi A6    25000          32000        5
7                 Audi A5    72000          19300        5
8                 Audi A8    20000          62000        3
9   Mercedez Benz C class    67000          22000        6
10  Mercedez Benz C class    83000          20000        7
11  Mercedez Benz C class    79000          21000        7
12  Mercedez Benz C class    59000          33000        5

In [38]:
model.predict([[45000,0,0,0,1,0]])

array([34486.13412229])

In [45]:
model.predict([[45000,5,0,0,0,0]])

array([34678.42209073])

In [46]:
#(#1)audi6,(2)audi8,(3)audi5,(4)mercedez,(5)bmw
model.predict([[45000,5,0,0,1,0]])

array([36742.14990138])

In [47]:
model.predict([[86000,7,0,0,0,1]])

array([11782.22879684])

In [51]:
model.score(x_train,x_test)

0.9740650664498051

In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('E:\csv files\cardata.csv')

In [2]:
df

car_models  totl_km  sell_price($)  car_age
0                  bmw x5    69000          18000        3
1                  bmw x5    35000          34000        3
2                  bmw x5    57000          26100        5
3                  bmw x5    22500          40000        2
4                  bmw x5    46000          31500        4
5                 Audi A5    59000          29400        4
6                 Audi A6    25000          32000        5
7                 Audi A5    72000          19300        5
8                 Audi A8    20000          62000        3
9   Mercedez Benz C class    67000          22000        6
10  Mercedez Benz C class    83000          20000        7
11  Mercedez Benz C class    79000          21000        7
12  Mercedez Benz C class    59000          33000        5

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le=LabelEncoder()

In [32]:
df.car_models=le.fit_transform(df[['car_models']])
df

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


car_models  totl_km  sell_price($)  car_age
0            4    69000          18000        3
1            4    35000          34000        3
2            4    57000          26100        5
3            4    22500          40000        2
4            4    46000          31500        4
5            0    59000          29400        4
6            1    25000          32000        5
7            0    72000          19300        5
8            2    20000          62000        3
9            3    67000          22000        6
10           3    83000          20000        7
11           3    79000          21000        7
12           3    59000          33000        5

In [36]:
x=df[['car_models','totl_km','car_age']].values
x

array([[    4, 69000,     3],
       [    4, 35000,     3],
       [    4, 57000,     5],
       [    4, 22500,     2],
       [    4, 46000,     4],
       [    0, 59000,     4],
       [    1, 25000,     5],
       [    0, 72000,     5],
       [    2, 20000,     3],
       [    3, 67000,     6],
       [    3, 83000,     7],
       [    3, 79000,     7],
       [    3, 59000,     5]], dtype=int64)

In [38]:
y=df[['sell_price($)']].values
y

array([[18000],
       [34000],
       [26100],
       [40000],
       [31500],
       [29400],
       [32000],
       [19300],
       [62000],
       [22000],
       [20000],
       [21000],
       [33000]], dtype=int64)

In [39]:
from sklearn.preprocessing import OneHotEncoder

In [44]:
ohe=OneHotEncoder(sparse=False)

In [50]:
df1=ohe.fit_transform(df[['car_models']])

In [51]:
df1

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.]])

In [63]:
df2=pd.DataFrame(df1,columns=['audia5','audi6','audi8','mercedizBenz','bmwx5'])

In [64]:
df2

audia5  audi6  audi8  mercedizBenz  bmwx5
0      0.0    0.0    0.0           0.0    1.0
1      0.0    0.0    0.0           0.0    1.0
2      0.0    0.0    0.0           0.0    1.0
3      0.0    0.0    0.0           0.0    1.0
4      0.0    0.0    0.0           0.0    1.0
5      1.0    0.0    0.0           0.0    0.0
6      0.0    1.0    0.0           0.0    0.0
7      1.0    0.0    0.0           0.0    0.0
8      0.0    0.0    1.0           0.0    0.0
9      0.0    0.0    0.0           1.0    0.0
10     0.0    0.0    0.0           1.0    0.0
11     0.0    0.0    0.0           1.0    0.0
12     0.0    0.0    0.0           1.0    0.0

In [62]:
df

car_models  totl_km  sell_price($)  car_age
0            4    69000          18000        3
1            4    35000          34000        3
2            4    57000          26100        5
3            4    22500          40000        2
4            4    46000          31500        4
5            0    59000          29400        4
6            1    25000          32000        5
7            0    72000          19300        5
8            2    20000          62000        3
9            3    67000          22000        6
10           3    83000          20000        7
11           3    79000          21000        7
12           3    59000          33000        5

In [65]:
df3=pd.concat([df,df2],axis=1)
df3

car_models  totl_km  sell_price($)  car_age  audia5  audi6  audi8  \
0            4    69000          18000        3     0.0    0.0    0.0   
1            4    35000          34000        3     0.0    0.0    0.0   
2            4    57000          26100        5     0.0    0.0    0.0   
3            4    22500          40000        2     0.0    0.0    0.0   
4            4    46000          31500        4     0.0    0.0    0.0   
5            0    59000          29400        4     1.0    0.0    0.0   
6            1    25000          32000        5     0.0    1.0    0.0   
7            0    72000          19300        5     1.0    0.0    0.0   
8            2    20000          62000        3     0.0    0.0    1.0   
9            3    67000          22000        6     0.0    0.0    0.0   
10           3    83000          20000        7     0.0    0.0    0.0   
11           3    79000          21000        7     0.0    0.0    0.0   
12           3    59000          33000        5     0.0    0.0    0.0   

    mercedizBenz  bmwx5  
0            0.0    1.0  
1            0.0    1.0  
2            0.0    1.0  
3            0.0    1.0  
4            0.0    1.0  
5            0.0    0.0  
6            0.0    0.0  
7            0.0    0.0  
8            0.0    0.0  
9            1.0    0.0  
10           1.0    0.0  
11           1.0    0.0  
12           1.0    0.0

In [72]:
X_train=df3.drop(['car_models','sell_price($)','audi8'],axis=1)
X_train

totl_km  car_age  audia5  audi6  mercedizBenz  bmwx5
0     69000        3     0.0    0.0           0.0    1.0
1     35000        3     0.0    0.0           0.0    1.0
2     57000        5     0.0    0.0           0.0    1.0
3     22500        2     0.0    0.0           0.0    1.0
4     46000        4     0.0    0.0           0.0    1.0
5     59000        4     1.0    0.0           0.0    0.0
6     25000        5     0.0    1.0           0.0    0.0
7     72000        5     1.0    0.0           0.0    0.0
8     20000        3     0.0    0.0           0.0    0.0
9     67000        6     0.0    0.0           1.0    0.0
10    83000        7     0.0    0.0           1.0    0.0
11    79000        7     0.0    0.0           1.0    0.0
12    59000        5     0.0    0.0           1.0    0.0

In [74]:
x_test=df['sell_price($)']

In [69]:
from sklearn import linear_model

In [70]:
model=linear_model.LinearRegression()

In [75]:
model.fit(X_train,x_test)

LinearRegression()

In [76]:
model.predict([[4500,5,0,0,0,1]])

array([51044.69428008])

In [82]:
model.predict([[45000,5,1,0,0,0]])

array([34678.42209073])

In [81]:
model.score(X_train,x_test)

0.9740650664498051